# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn
from matplotlib import pyplot as plt
from sympy.physics.units import planck_time

from ours.utils.CT_dataset import toZeroOne


# %% auto 0
# __all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images with circular mask."""

    def __init__(self, patch_size=None, eps=1e-3, image_size=256, radius=118, device=torch.device('cpu'), step=1):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.register_buffer('mask', self.create_mask(image_size, radius, patch_size, step).to(device))
        self.ori_mask = self.mask
        self.step = step

    @staticmethod
    def create_mask(image_size, radius, patch_size=None, step=1):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size, step)
        return mask # Shape: (1, 1, H, W)

    def forward(self, x1, x2, wei1=None, wei2=None):
        if wei1 is None:
            wei1 = torch.ones_like(x1, device=x1.device, dtype=x1.dtype)
        if wei2 is None:
            wei2 = torch.ones_like(x1, device=x1.device, dtype=x1.dtype)
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size, self.step)
            x2 = to_patches(x2, self.patch_size, self.step)
            wei1 = to_patches(wei1, self.patch_size, self.step)
            wei2 = to_patches(wei2, self.patch_size, self.step)

        assert x1.shape == x2.shape, "Input images must be the same size"

        x1 = x1[:, self.valid_idx, :, :]
        x2 = x2[:, self.valid_idx, :, :]
        wei1 = wei1[:, self.valid_idx, :, :]
        wei2 = wei2[:, self.valid_idx, :, :]
        x1 = x1 * self.mask
        x2 = x2 * self.mask
        wei1 = wei1 * self.mask
        wei2 = wei2 * self.mask

        _, c, h, w = x1.shape

        wei = wei1 * wei2
        mean1 = (x1 * wei1).sum(dim=[-2, -1], keepdim=True) / ((wei1).sum(dim=[-2, -1], keepdim=True) + self.eps)
        mean2 = (x2 * wei2).sum(dim=[-2, -1], keepdim=True) / ((wei2).sum(dim=[-2, -1], keepdim=True) + self.eps)

        numerator = ((x1 - mean1) * (x2 - mean2) * wei).sum(dim=[-2, -1])
        denom1 = torch.sqrt(((wei1 * (x1 - mean1)) ** 2).sum(dim=[-2, -1]))
        denom2 = torch.sqrt(((wei2 * (x2 - mean2)) ** 2).sum(dim=[-2, -1]))

        score = (numerator / (denom1 * denom2 + 1e-6))
        score = score.sum()
        score = (score / c).squeeze()

        return score

    def norm(self, x, wei):
        mask = self.mask.expand_as(x)

        mu = (x * mask * wei).sum(dim=[-2, -1], keepdim=True) / ((mask * wei).sum(dim=[-2, -1], keepdim=True) + self.eps)
        x_centered = (x - mu) * mask * wei
        var = (wei * (x_centered ** 2).sum(dim=[-2, -1], keepdim=True) / (mask).sum(dim=[-2, -1], keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)

    def set_mask(self, tube_mask):

        if self.patch_size is not None:
            tube_mask = to_patches(tube_mask, self.patch_size, self.step)
        self.mask = tube_mask * self.ori_mask
        # plt.figure()
        # plt.imshow(self.mask.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show()

        # valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 30
        valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 0
        idx = torch.where(~valid)
        valid_idx = idx[1]
        self.valid_idx = valid_idx
        self.mask = self.mask[:, valid_idx, :, :]
        self.mask_sum = self.mask.sum()


class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""
    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5, device=torch.device('cpu'), step=[1]):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size, device=device, step=s) for patch_size, s in zip(patch_sizes, step)
        ]
        self.patch_weights = patch_weights
        self.step = step

    def forward(self, x1, x2, wei1=None, wei2=None):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2, wei1, wei2))
        return torch.stack(scores, dim=0).sum(dim=0)

    def set_mask(self, tube_mask):
        for ncc in self.nccs:
            ncc.set_mask(tube_mask)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size, step=1):
    # x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    x = x.unfold(2, patch_size, step=step).unfold(3, patch_size, step=step).contiguous()
    # x = x.unfold(2, patch_size, step=patch_size // 2).unfold(3, patch_size, step=patch_size // 2).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

