# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn
from matplotlib import pyplot as plt
from sympy.physics.units import planck_time


# %% auto 0
# __all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images with circular mask."""

    def __init__(self, patch_size=None, eps=1e-4, image_size=256, radius=120, device=torch.device('cpu')):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.register_buffer('mask', self.create_mask(image_size, radius, patch_size).to(device))


    @staticmethod
    def create_mask(image_size, radius, patch_size=None):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size)
        return mask # Shape: (1, 1, H, W)

    def set_weight_mask(self, weight_mask):
        """Set a weight mask for NCC calculation.
        Args:
            weight_mask (torch.Tensor): Weight tensor of shape (1, 1, H, W) or similar broadcastable shape.
        """
        if self.patch_size is not None:
            weight_mask = to_patches(weight_mask, self.patch_size)
        self.weight_mask = weight_mask.to(self.mask.device)

    def forward(self, x1, x2):
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size)
            x2 = to_patches(x2, self.patch_size)

        assert x1.shape == x2.shape, "Input images must be the same size"

        x1 = x1[:, self.valid_idx, :, :]
        x2 = x2[:, self.valid_idx, :, :]
        x1 = x1 * self.mask
        x2 = x2 * self.mask

        _, c, h, w = x1.shape
        x1, x2 = self.norm(x1), self.norm(x2)

        final_weight = self.mask
        if self.weight_mask is not None:
            # Ensure weight_mask has the same spatial dimensions
            weight_mask_selected = self.weight_mask[:, self.valid_idx, :, :]
            final_weight = self.mask * weight_mask_selected

        score = (x1 * x2 * final_weight).sum(dim=[-3, -2, -1])
        # effective_pixels = self.mask_sum
        effective_pixels = final_weight.sum(dim=[-3, -2, -1])
        score /= effective_pixels + self.eps

        return score

    def norm(self, x):
        mask = self.mask.expand_as(x)

        mu = (x * mask).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        x_centered = (x - mu) * mask
        var = (x_centered ** 2).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)

    def set_mask(self, tube_mask):
        if self.patch_size is not None:
            tube_mask = to_patches(tube_mask, self.patch_size)
        self.mask = tube_mask * self.mask
        # plt.figure()
        # plt.imshow(self.mask.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show()

        valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 5
        idx = torch.where(~valid)
        valid_idx = idx[1]
        self.valid_idx = valid_idx
        self.mask = self.mask[:, valid_idx, :, :]
        self.mask_sum = self.mask.sum()


class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""
    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5, device=torch.device('cpu')):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size, device=device) for patch_size in patch_sizes
        ]
        self.patch_weights = patch_weights

    def forward(self, x1, x2):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2))
        return torch.stack(scores, dim=0).sum(dim=0)

    def set_mask(self, tube_mask):
        for ncc in self.nccs:
            ncc.set_mask(tube_mask)

    def set_weight_mask(self, weight_mask):
        for ncc in self.nccs:
            ncc.set_weight_mask(weight_mask)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size):
    x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

