# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn
from matplotlib import pyplot as plt
from sympy.physics.units import planck_time


# %% auto 0
# __all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images with circular mask."""

    def __init__(self, patch_size=None, eps=1e-3, image_size=256, radius=120, device=torch.device('cpu'), step=1):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.step = step

    @staticmethod
    def create_mask(image_size, radius, patch_size=None, step=1):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size, step)
        return mask # Shape: (1, 1, H, W)

    def forward(self, x1, x2, mask=None):
        if mask == None: mask = torch.ones_like(x1).to(x1.device)
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size, step=self.step)
            x2 = to_patches(x2, self.patch_size, step=self.step)
            mask = to_patches(mask, self.patch_size, step=self.step).to(x1.device)
        # plt.figure()
        # plt.imshow(mask.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show()

        valid = mask.sum(dim=[-2, -1], keepdim=True) <= 30
        idx = torch.where(~valid)
        valid_idx = idx[1]
        valid_idx = valid_idx
        mask = mask[:, valid_idx, :, :]

        assert x1.shape == x2.shape, "Input images must be the same size"

        x1 = x1[:, valid_idx, :, :]
        x2 = x2[:, valid_idx, :, :]
        x1 = x1 * mask
        x2 = x2 * mask

        _, c, h, w = x1.shape
        x1, x2 = self.norm(x1, mask), self.norm(x2, mask)

        score = torch.einsum("b...,b...->b", x1, x2)
        effective_pixels = mask.sum() # Total valid pixels per batch
        score /= effective_pixels + self.eps

        return score

    def norm(self, x, mask):
        mu = (x * mask).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        x_centered = (x - mu) * mask
        var = (x_centered ** 2).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)

class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""
    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5, device=torch.device('cpu'), step=[1]):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size, device=device, step=s) for patch_size, s in zip(patch_sizes, step)
        ]
        self.patch_weights = patch_weights

    def forward(self, x1, x2, mask=None):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2, mask))
        return torch.stack(scores, dim=0).sum(dim=0)

    def set_mask(self, tube_mask):
        for ncc in self.nccs:
            ncc.set_mask(tube_mask)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size, step=1):
    # x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    x = x.unfold(2, patch_size, step=step).unfold(3, patch_size, step=step).contiguous()
    # x = x.unfold(2, patch_size, step=patch_size // 2).unfold(3, patch_size, step=patch_size // 2).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")


class IoU2d(torch.nn.Module):
    """Compute Intersection over Union (IoU) with circular mask at a single scale."""

    def __init__(self, patch_size=None, eps=1e-4, image_size=256, radius=120,
                 threshold=0.5, device=torch.device('cpu')):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.threshold = threshold

    @staticmethod
    def create_mask(image_size, radius, patch_size=None):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size)
        return mask  # Shape: (1, 1, H, W)

    def forward(self, pred, target):
        # Convert to patches if needed
        if self.patch_size is not None:
            pred = to_patches(pred, self.patch_size)
            target = to_patches(target, self.patch_size)
        pred = pred[:, self.valid_idx, ...]
        target = target[:, self.valid_idx, ...]

        # Apply circular mask
        pred_masked = pred * self.mask
        target_masked = target * self.mask

        # Calculate intersection and union
        intersection = (pred_masked * target_masked).sum(dim=[-2, -1])
        union = (pred_masked + target_masked).sum(dim=[-2, -1]) - intersection

        # Compute IoU per patch
        iou_per_patch = intersection / (union + self.eps)

        # Average IoU across all valid patches
        return iou_per_patch.mean(dim=1)

    def set_mask(self, tube_mask):
        if self.patch_size is not None:
            tube_mask = to_patches(tube_mask, self.patch_size)
        self.mask = tube_mask
        # plt.figure()
        # plt.imshow(self.mask.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show()

        valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 20
        idx = torch.where(~valid)
        valid_idx = idx[1]
        self.valid_idx = valid_idx
        self.mask = self.mask[:, valid_idx, :, :]


class MultiscaleIoU2d(torch.nn.Module):
    """Compute IoU at multiple scales with circular mask."""

    def __init__(self, patch_sizes=[None], scale_weights=None,
                 image_size=256, radius=120, threshold=0.5,
                 eps=1e-8, device=torch.device('cpu')):
        super().__init__()
        self.scale_weights = scale_weights or [1.0] * len(patch_sizes)

        self.iou_computers = torch.nn.ModuleList([
            IoU2d(
                patch_size=size,
                eps=eps,
                image_size=image_size,
                radius=radius,
                threshold=threshold,
                device=device
            ) for size in patch_sizes
        ])

    def forward(self, pred, target):
        """Compute weighted average IoU across multiple scales."""
        scale_ious = []
        for weight, iou_computer in zip(self.scale_weights, self.iou_computers):
            iou = iou_computer(pred, target)
            scale_ious.append(weight * iou)

        # Combine results from different scales
        return torch.stack(scale_ious).sum(dim=0)

    def set_mask(self, tube_mask):
        for iou in self.iou_computers:
            iou.set_mask(tube_mask)

