# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn
from matplotlib import pyplot as plt
from sympy.physics.units import planck_time


# %% auto 0
# __all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images with circular mask."""

    def __init__(self, patch_size=None, eps=1e-3, image_size=256, radius=118, device=torch.device('cpu')):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.register_buffer('mask', self.create_mask(image_size, radius, patch_size).to(device))

        valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 30
        valid_idx = torch.where(~valid)[1]
        self.valid_idx = valid_idx
        self.ori_mask = self.mask
        self.mask = self.mask[:, valid_idx, :, :]
        self.mask_sum = self.mask.sum()

    @staticmethod
    def create_mask(image_size, radius, patch_size=None):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size)
        return mask # Shape: (1, 1, H, W)

    def forward(self, x1, x2, weight_map=None):
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size)
            x2 = to_patches(x2, self.patch_size)

        # Apply circular mask
        if (self.valid_idx.shape[0] != self.ori_mask.shape[1]):
            x1 = x1[:, self.valid_idx, :, :]
            x2 = x2[:, self.valid_idx, :, :]
        x1 = x1 * self.mask
        x2 = x2 * self.mask
        if weight_map is not None and self.patch_size is not None:
            weight_map = to_patches(weight_map, self.patch_size)
            weight_map = weight_map[:, self.valid_idx, :, :] * self.mask

        # _, c, h, w = x1.shape

        if weight_map is None:
            x1, x2 = self.norm(x1), self.norm(x2)

            score = torch.einsum("b...,b...->b", x1, x2)
            effective_pixels = self.mask_sum  # Total valid pixels per batch
            score /= effective_pixels + self.eps
        else:
            x1, x2 = self.norm(x1), self.norm(x2)

            score = torch.einsum("b...,b...,b...->b", x1, x2, weight_map)
            effective_pixels = self.mask_sum  # Total valid pixels per batch
            score /= effective_pixels + self.eps

        return score

    def norm(self, x, weight_map=None):
        mask = self.mask

        mu = (x * mask).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        x_centered = (x - mu) * mask
        var = (x_centered ** 2).sum(dim=[-2, -1], keepdim=True) / (mask.sum(dim=[-2, -1], keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)

    def generate_weight_map(self, img, dark_power=2.0):
        intensity = (img - img.min()) / (img.max() - img.min())
        weight_map = 1.0 - intensity
        # weight_map = torch.ones_like(img)
        # weight_map[intensity < 0.8] = 0.2
        # weight_map[intensity < 0.6] = 0.7
        # weight_map[intensity >= 0.8] = 0.1
        # plt.figure()
        # plt.imshow(weight_map.cpu().squeeze(0).squeeze(0), cmap='gray')
        # plt.show()
        return weight_map ** dark_power


class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""

    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5, device=torch.device('cpu')):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size, device=device) for patch_size in patch_sizes
        ]
        self.patch_weights = patch_weights

    def forward(self, x1, x2, weight_map=None):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2, weight_map))
        return torch.stack(scores, dim=0).sum(dim=0)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size):
    x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

