# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn
from matplotlib import pyplot as plt
from sympy.physics.units import planck_time

from ours.utils.CT_dataset import toZeroOne


# %% auto 0
# __all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images with circular mask."""

    def __init__(self, patch_size=None, eps=1e-3, image_size=256, radius=118, device=torch.device('cpu'), step=1):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps
        self.image_size = image_size
        self.radius = radius
        self.register_buffer('mask', self.create_mask(image_size, radius, patch_size, step).to(device))
        self.ori_mask = self.mask
        self.step = step

    @staticmethod
    def create_mask(image_size, radius, patch_size=None, step=1):
        center = (image_size - 1) / 2  # Center at 127.5 for 256x256
        y = torch.arange(image_size, dtype=torch.float32)
        x = torch.arange(image_size, dtype=torch.float32)
        yy, xx = torch.meshgrid(y, x, indexing='ij')
        dist_sq = (xx - center) ** 2 + (yy - center) ** 2
        mask = (dist_sq <= radius ** 2).float().unsqueeze(0).unsqueeze(0)
        if patch_size is not None:
            mask = to_patches(mask, patch_size, step)
        return mask # Shape: (1, 1, H, W)

    def forward(self, x1, x2, wei=None):
        x1 = toZeroOne(x1)
        x2 = toZeroOne(x2)
        if wei is None:
            wei = torch.ones_like(x1, device=x1.device, dtype=x1.dtype)
        wei = compute_patch_weights_from_mask(wei, self.patch_size, self.step)
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size, self.step)
            x2 = to_patches(x2, self.patch_size, self.step)

        assert x1.shape == x2.shape, "Input images must be the same size"

        x1 = x1[:, self.valid_idx, :, :]
        x2 = x2[:, self.valid_idx, :, :]
        wei = wei[:, self.valid_idx]
        x1 = x1 * self.mask
        x2 = x2 * self.mask

        _, c, h, w = x1.shape

        mean1 = (x1).sum(dim=[-2, -1], keepdim=True) / ((self.mask).sum(dim=[-2, -1], keepdim=True) + self.eps)
        mean2 = (x2).sum(dim=[-2, -1], keepdim=True) / ((self.mask).sum(dim=[-2, -1], keepdim=True) + self.eps)

        numerator = ((x1 - mean1) * (x2 - mean2)).sum(dim=[-2, -1])
        denom1 = torch.sqrt(((x1 - mean1) ** 2).sum(dim=[-2, -1]))
        denom2 = torch.sqrt(((x2 - mean2) ** 2).sum(dim=[-2, -1]))

        score = (numerator / (denom1 * denom2 + 1e-6))
        # for i in range(score.shape[1]):
        #     plt.figure()
        #     plt.imshow(x1[0][i].detach().cpu(), cmap='gray')
        #     plt.title(f"{score[0][i]}")
        #     plt.show()
        #     plt.figure()
        #     plt.imshow(x2[0][i].detach().cpu(), cmap='gray')
        #     plt.title(f"{score[0][i]}")
        #     plt.show()
        #     print(score[0][i])
        # if hasattr(self, 'wei') and self.wei is not None:
        #     score *= self.wei
        # score = score.sum()
        # score = (score / c).squeeze()

        score = (score * wei).sum()
        score /= wei.sum()

        return score

    def norm(self, x, wei):
        mask = self.mask.expand_as(x)

        mu = (x * mask * wei).sum(dim=[-2, -1], keepdim=True) / ((mask * wei).sum(dim=[-2, -1], keepdim=True) + self.eps)
        x_centered = (x - mu) * mask * wei
        var = (wei * (x_centered ** 2).sum(dim=[-2, -1], keepdim=True) / (mask).sum(dim=[-2, -1], keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)

    def set_mask(self, tube_mask):

        if self.patch_size is not None:
            tube_mask = to_patches(tube_mask, self.patch_size, self.step)
        self.mask = tube_mask * self.ori_mask
        # plt.figure()
        # plt.imshow(self.mask.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show()

        # valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 30
        valid = self.mask.sum(dim=[-2, -1], keepdim=True) <= 100
        idx = torch.where(~valid)
        valid_idx = idx[1]
        self.valid_idx = valid_idx
        self.mask = self.mask[:, valid_idx, :, :]
        self.mask_sum = self.mask.sum()

        if hasattr(self, 'wei') and self.wei is not None:
            self.wei = self.wei[:, valid_idx]

    def set_wei(self, mask, step):
        if hasattr(self, 'patch_size') and self.patch_size is not None:
            wei = compute_patch_weights_from_mask(mask, self.patch_size, step)
            # a = (wei < 0.05).float().sum()
            self.wei = wei


class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""
    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5, device=torch.device('cpu'), step=[1]):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size, device=device, step=s) for patch_size, s in zip(patch_sizes, step)
        ]
        self.patch_weights = patch_weights
        self.step = step

    def forward(self, x1, x2, wei=None):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2, wei))
        return torch.stack(scores, dim=0).sum(dim=0)

    def set_mask(self, tube_mask):
        for ncc in self.nccs:
            ncc.set_mask(tube_mask)

    def set_wei(self, mask):
        for ncc, s in zip(self.nccs, self.step):
            ncc.set_wei(mask, s)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size, step=1):
    # x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    x = x.unfold(2, patch_size, step=step).unfold(3, patch_size, step=step).contiguous()
    # x = x.unfold(2, patch_size, step=patch_size // 2).unfold(3, patch_size, step=patch_size // 2).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

def compute_patch_weights_from_mask(mask: torch.Tensor,
                                   patch_size: int,
                                   step: int = 1,
                                   eps: float = 1e-6) -> torch.Tensor:
    """
    根据二值 mask 计算每个 patch 的权重（1 的像素占比）

    Args:
        mask: torch.Tensor, shape (B, 1, H, W), 值域为 0 或 1
        patch_size: int, patch 的大小（如 64）
        step: int, unfold 时的步长（默认1，表示密集采样）
        eps: float, 防止除零

    Returns:
        patch_weights: torch.Tensor, shape (B, N),
                        N = ((H - patch_size) // step + 1) * ((W - patch_size) // step + 1)
                        每个值在 [0, 1] 之间，表示该 patch 中有效像素的比例
    """
    assert mask.ndim == 4 and mask.shape[1] == 1, "mask 应为 (B, 1, H, W)"
    assert mask.dtype in (torch.float32, torch.float64, torch.bool, torch.uint8, torch.int32, torch.int64)

    B, _, H, W = mask.shape

    # Step 1: 分 patch
    mask_patches = to_patches(mask, patch_size, step)  # (B, N, patch_size, patch_size)

    # Step 2: 计算每个 patch 中 1 的数量
    valid_pixels = mask_patches.sum(dim=[-2, -1])  # (B, N)

    # Step 3: 每个 patch 总像素数
    total_pixels_per_patch = patch_size * patch_size

    # Step 4: 计算占比作为权重
    weights = valid_pixels / (total_pixels_per_patch + eps)  # (B, N)
    weights = (weights - 0) / (weights.max() - 0 + 1e-8)

    return weights  # shape: (B, N)

