# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/03_registration.ipynb.

# %% auto 0
__all__ = ['PoseRegressor', 'SparseRegistration', 'VectorizedNormalizedCrossCorrelation2d']

import matplotlib.pyplot as plt
import numpy as np
# %% ../notebooks/api/03_registration.ipynb 3
import timm
import torch

from diffpose.calibration import RigidTransform, convert
from ours.dataset.CT_dataset import Transforms
# from diffpose.deepfluoro import Transforms


# %% ../notebooks/api/03_registration.ipynb 5
# from .calibration import RigidTransform, convert


class PoseRegressor(torch.nn.Module):
    """
    A PoseRegressor is comprised of a pretrained backbone model that extracts features
    from an input X-ray and two linear layers that decode these features into rotational
    and translational camera pose parameters, respectively.
    """

    def __init__(
        self,
        model_name,
        parameterization,
        convention=None,
        pretrained=False,
        **kwargs,
    ):
        super().__init__()

        self.parameterization = parameterization
        self.convention = convention
        n_angular_components = N_ANGULAR_COMPONENTS[parameterization]

        # Get the size of the output from the backbone
        self.backbone = timm.create_model(
            model_name,
            pretrained,
            num_classes=0,
            in_chans=1,
            **kwargs,
        )
        output = self.backbone(torch.randn(1, 1, 256, 256)).shape[-1]
        self.xyz_regression = torch.nn.Linear(output, 3)
        self.rot_regression = torch.nn.Linear(output, n_angular_components)

    def forward(self, x):
        x = self.backbone(x)
        rot = self.rot_regression(x)
        xyz = self.xyz_regression(x)
        return convert(
            [rot, xyz],
            input_parameterization=self.parameterization,
            output_parameterization="se3_exp_map",
            input_convention=self.convention,
        )

# %% ../notebooks/api/03_registration.ipynb 6
N_ANGULAR_COMPONENTS = {
    "axis_angle": 3,
    "euler_angles": 3,
    "se3_log_map": 3,
    "quaternion": 4,
    "rotation_6d": 6,
    "rotation_10d": 10,
    "quaternion_adjugate": 10,
}

# %% ../notebooks/api/03_registration.ipynb 11
from diffdrr.detector import make_xrays
from diffdrr.drr import DRR
from diffdrr.siddon import siddon_raycast




class SparseRegistration(torch.nn.Module):
    def __init__(
        self,
        drr: DRR,
        pose: RigidTransform,
        parameterization: str,
        convention: str = None,
        features=None,  # Used to compute biased estimate of mNCC
        n_patches: int = None,  # If n_patches is None, render the whole image
        patch_size: int = 13
    ):
        super().__init__()
        self.drr = drr

        # Parse the input pose
        rotation, translation = convert(
            pose,
            input_parameterization="se3_exp_map",
            output_parameterization=parameterization,
            output_convention=convention,
        )
        self.parameterization = parameterization
        self.convention = convention
        self.rotation = torch.nn.Parameter(rotation)
        self.translation = torch.nn.Parameter(translation)

        # Crop pixels off the edge such that pixels don't fall outside the image
        self.n_patches = n_patches
        self.patch_size = patch_size
        self.patch_radius = self.patch_size // 2 + 1
        self.height = self.drr.detector.height
        self.width = self.drr.detector.width
        self.f_height = self.height - 2 * self.patch_radius
        self.f_width = self.width - 2 * self.patch_radius

        # Define the distribution over patch centers
        if features is None:
            features = torch.ones(
                self.height, self.width, device=self.rotation.device
            ) / (self.height * self.width)
        self.patch_centers = torch.distributions.categorical.Categorical(
            probs=features.squeeze()[
                self.patch_radius : -self.patch_radius,
                self.patch_radius : -self.patch_radius,
            ].flatten()
        )

        self.transforms = Transforms(self.height)

    def forward(self, n_patches=None, patch_size=None):
        # Parse initial density
        if not hasattr(self.drr, "density"):
            self.drr.set_bone_attenuation_multiplier(
                self.drr.bone_attenuation_multiplier
            )

        if n_patches is not None or patch_size is not None:
            self.n_patches = n_patches
            self.patch_size = patch_size

        # Make the mask for sparse rendering
        if self.n_patches is None:
            mask = torch.ones(
                1,
                self.height,
                self.width,
                dtype=torch.bool,
                device=self.rotation.device,
            )
        else:
            mask = torch.zeros(
                self.n_patches,
                self.height,
                self.width,
                dtype=torch.bool,
                device=self.rotation.device,
            )
            radius = self.patch_size // 2
            idxs = self.patch_centers.sample(sample_shape=torch.Size([self.n_patches]))
            idxs, jdxs = (
                idxs // self.f_height + self.patch_radius,
                idxs % self.f_width + self.patch_radius,
            )

            idx = torch.arange(-radius, radius + 1, device=self.rotation.device)
            patches = torch.cartesian_prod(idx, idx).expand(self.n_patches, -1, -1)
            patches = patches + torch.stack([idxs, jdxs], dim=-1).unsqueeze(1)
            patches = torch.concat(
                [
                    torch.arange(self.n_patches, device=self.rotation.device)
                    .unsqueeze(-1)
                    .expand(-1, self.patch_size**2)
                    .unsqueeze(-1),
                    patches,
                ],
                dim=-1,
            )
            mask[
                patches[..., 0],
                patches[..., 1],
                patches[..., 2],
            ] = True

        circle_mask = create_circle_mask(256, 121).expand(n_patches, -1, -1).to(self.rotation.device)
        circle_mask = (circle_mask & mask)

        # Get the source and target
        pose = convert(
            [self.rotation, self.translation],
            input_parameterization=self.parameterization,
            output_parameterization="se3_exp_map",
            input_convention=self.convention,
        )
        source, target = make_xrays(
            pose,
            self.drr.detector.source,
            self.drr.detector.target,
        )

        # Render the sparse image
        target_print = target
        target = target[mask.any(dim=0).view(1, -1)]
        img = siddon_raycast(source, target, self.drr.density, self.drr.spacing).to(torch.float32)
        img_print = siddon_raycast(source, target_print, self.drr.density, self.drr.spacing).to(torch.float32)
        img_print = self.drr.reshape_transform(img_print, batch_size=len(self.rotation))
        img_print = self.transforms(img_print)
        if self.n_patches is None:
            img = self.drr.reshape_transform(img, batch_size=len(self.rotation))

        # img_print = img.detach().clone()
        # plt.figure()
        # plt.imshow(img_print.cpu().squeeze(0).permute(1, 2, 0), cmap='gray')
        # plt.show(
        return img, mask, img_print, circle_mask

    def get_current_pose(self):
        return convert(
            [self.rotation, self.translation],
            input_parameterization=self.parameterization,
            output_parameterization="se3_exp_map",
            input_convention=self.convention,
        )

# %% ../notebooks/api/03_registration.ipynb 13
def preprocess(x, reverse=False, eps=1e-4):
    x = (x - x.min()) / (x.max() - x.min() + eps)
    if reverse:
        x = 1 - x
    return (x - 0.3080) / 0.1494


def pred_to_patches(pred_img, mask, n_patches, patch_size):
    return pred_img.expand(-1, n_patches, -1)[..., mask[..., mask.any(dim=0)]].reshape(
        1, n_patches, -1
    )


def img_to_patches(img, mask, n_patches, patch_size):
    return img.expand(-1, n_patches, -1, -1)[..., mask].reshape(1, n_patches, -1)


def mask_to_img(img, mask):
    return img[..., mask.any(dim=0)]


def vector_to_img(pred_img, mask):
    patches = [pred_img]
    filled = torch.zeros(1, 1, *mask[0].shape, device=pred_img.device)
    filled[...] = torch.nan
    for idx in range(len(mask)):
        patch = pred_img[:, mask[idx][mask.any(dim=0)]]
        filled[..., mask[idx]] = patch
        patches.append(patch)
    return filled

def create_circle_mask(image_size, radius):
    center = (image_size - 1) / 2  # Center at 127.5 for 256x256
    y = torch.arange(image_size, dtype=torch.float32)
    x = torch.arange(image_size, dtype=torch.float32)
    yy, xx = torch.meshgrid(y, x, indexing='ij')
    dist_sq = (xx - center) ** 2 + (yy - center) ** 2
    mask = (dist_sq <= radius ** 2)
    return mask

# %% ../notebooks/api/03_registration.ipynb 14
class VectorizedNormalizedCrossCorrelation2d(torch.nn.Module):
    def __init__(self, eps=1e-4):
        super().__init__()
        self.eps = eps

    def forward(self, img, pred_img, mask, circle_mask, n_patches, patch_size, reverse=False):
        pred_img = preprocess(pred_img, reverse).unsqueeze(0)
        sub_img = mask_to_img(img, mask)
        pred_patches = pred_to_patches(pred_img, mask, n_patches, patch_size)
        img_patches = img_to_patches(img, mask, n_patches, patch_size)

        circle_mask_img = circle_mask.any(dim=0).float().unsqueeze(0).unsqueeze(0)
        sub_circle_mask = circle_mask_img[..., mask.any(dim=0)]
        circle_mask_patches = img_to_patches(circle_mask_img, mask, n_patches, patch_size)

        local_ncc = self.forward_compute(pred_patches, img_patches, circle_mask_patches)
        global_ncc = self.forward_compute(pred_img, sub_img, sub_circle_mask)
        return (local_ncc + global_ncc) / 2

    def forward_compute(self, x1, x2, mask=None):
        assert x1.shape == x2.shape, "Input images must be the same size"
        invalid = mask.sum(dim=-1, keepdim=True) <= 5
        valid_idx = torch.where(~invalid)[1]
        x1 = x1[:, valid_idx, :]
        x2 = x2[:, valid_idx, :]
        mask = mask[:, valid_idx, :]
        x1, x2 = self.norm(x1, mask), self.norm(x2, mask)
        ncc = (x1 * x2).sum() / mask.sum()
        return ncc

    def norm(self, x, mask=None):
        mu = (x * mask).sum(dim=-1, keepdim=True) / (mask.sum(dim=-1, keepdim=True) + self.eps)
        x_centered = (x - mu) * mask
        var = (x_centered ** 2).sum(dim=-1, keepdim=True) / (mask.sum(dim=-1, keepdim=True) + self.eps)
        std = var.sqrt()
        return x_centered / (std + self.eps)
