# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/api/05_metrics.ipynb.

# %% ../notebooks/api/05_metrics.ipynb 3
from __future__ import annotations

import torch
import torch.nn as nn

# %% auto 0
__all__ = ['NormalizedCrossCorrelation2d', 'MultiscaleNormalizedCrossCorrelation2d', 'GradientNormalizedCrossCorrelation2d']

# %% ../notebooks/api/05_metrics.ipynb 4
class NormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images."""

    def __init__(self, patch_size=None, eps=1e-5):
        super().__init__()
        self.patch_size = patch_size
        self.eps = eps

    def forward(self, x1, x2):
        if self.patch_size is not None:
            x1 = to_patches(x1, self.patch_size)
            x2 = to_patches(x2, self.patch_size)
        assert x1.shape == x2.shape, "Input images must be the same size"
        _, c, h, w = x1.shape
        x1, x2 = self.norm(x1), self.norm(x2)

        score = (x1 * x2).sum(dim=[-2, -1])
        if hasattr(self, 'wei') and self.wei is not None:
            score = (score * self.wei).sum() / self.wei.sum()
        else:
            score = score.sum() / c
        score = score / (h * w)
        return score

    def norm(self, x):
        mu = x.mean(dim=[-1, -2], keepdim=True)
        var = x.var(dim=[-1, -2], keepdim=True, correction=0) + self.eps
        std = var.sqrt()
        return (x - mu) / std

    def set_wei(self, mask):
        if hasattr(self, 'patch_size') and self.patch_size is not None:
            wei = compute_patch_weights_from_mask(mask, self.patch_size)
            # a = (wei < 0.05).float().sum()
            self.wei = wei


class MultiscaleNormalizedCrossCorrelation2d(torch.nn.Module):
    """Compute Normalized Cross Correlation between two batches of images at multiple scales."""

    def __init__(self, patch_sizes=[None], patch_weights=[1.0], eps=1e-5):
        super().__init__()

        assert len(patch_sizes) == len(patch_weights), "Each scale must have a weight"
        self.nccs = [
            NormalizedCrossCorrelation2d(patch_size) for patch_size in patch_sizes
        ]
        self.patch_weights = patch_weights

    def forward(self, x1, x2):
        scores = []
        for weight, ncc in zip(self.patch_weights, self.nccs):
            scores.append(weight * ncc(x1, x2))
        return torch.stack(scores, dim=0).sum(dim=0)

    def set_wei(self, mask):
        for ncc in self.nccs:
            ncc.set_wei(mask)

# %% ../notebooks/api/05_metrics.ipynb 5
from einops import rearrange


def to_patches(x, patch_size):
    x = x.unfold(2, patch_size, step=1).unfold(3, patch_size, step=1).contiguous()
    return rearrange(x, "b c p1 p2 h w -> b (c p1 p2) h w")

def compute_patch_weights_from_mask(mask: torch.Tensor,
                                   patch_size: int,
                                   step: int = 1,
                                   eps: float = 1e-6) -> torch.Tensor:
    """
    根据二值 mask 计算每个 patch 的权重（1 的像素占比）

    Args:
        mask: torch.Tensor, shape (B, 1, H, W), 值域为 0 或 1
        patch_size: int, patch 的大小（如 64）
        step: int, unfold 时的步长（默认1，表示密集采样）
        eps: float, 防止除零

    Returns:
        patch_weights: torch.Tensor, shape (B, N),
                        N = ((H - patch_size) // step + 1) * ((W - patch_size) // step + 1)
                        每个值在 [0, 1] 之间，表示该 patch 中有效像素的比例
    """
    assert mask.ndim == 4 and mask.shape[1] == 1, "mask 应为 (B, 1, H, W)"
    assert mask.dtype in (torch.float32, torch.float64, torch.bool, torch.uint8, torch.int32, torch.int64)

    B, _, H, W = mask.shape

    # Step 1: 分 patch
    mask_patches = to_patches(mask, patch_size)  # (B, N, patch_size, patch_size)

    # Step 2: 计算每个 patch 中 1 的数量
    valid_pixels = mask_patches.sum(dim=[-2, -1])  # (B, N)

    # Step 3: 每个 patch 总像素数
    total_pixels_per_patch = patch_size * patch_size

    # Step 4: 计算占比作为权重
    weights = valid_pixels / (total_pixels_per_patch + eps)  # (B, N)
    weights = (weights - 0) / (weights.max() - 0 + 1e-8)
    return weights  # shape: (B, N)

# %% ../notebooks/api/05_metrics.ipynb 6
class GradientNormalizedCrossCorrelation2d(NormalizedCrossCorrelation2d):
    """Compute Normalized Cross Correlation between the image gradients of two batches of images."""

    def __init__(self, patch_size=None, sigma=1.0, **kwargs):
        super().__init__(patch_size, **kwargs)
        self.sobel = Sobel(sigma)

    def forward(self, x1, x2):
        return super().forward(self.sobel(x1), self.sobel(x2))

# %% ../notebooks/api/05_metrics.ipynb 7
from torchvision.transforms.functional import gaussian_blur


class Sobel(torch.nn.Module):
    def __init__(self, sigma):
        super().__init__()
        self.sigma = sigma
        self.filter = torch.nn.Conv2d(
            in_channels=1,
            out_channels=2,  # X- and Y-gradients
            kernel_size=3,
            stride=1,
            padding=1,  # Return images of the same size as inputs
            bias=False,
        )

        Gx = torch.tensor([[1, 0, -1], [2, 0, -2], [1, 0, -1]]).to(torch.float32)
        Gy = torch.tensor([[1, 2, 1], [0, 0, 0], [-1, -2, -1]]).to(torch.float32)
        G = torch.stack([Gx, Gy]).unsqueeze(1)
        self.filter.weight = torch.nn.Parameter(G, requires_grad=False)

    def forward(self, img):
        x = gaussian_blur(img, 5, self.sigma)
        x = self.filter(img)
        return x
